### ISSUE TITLE
Release Code and Ckpt

### ISSUE THREAD

**Issue by MahdiMohseni0033** [Jeff-LiangF/FlowVid#1]
Thanks for your amazing work. I couldn't wait to release the code. Could you please let me know roughly when you are planning to release it?

**Comment by ghyghoo8** [comment]
mark

**Comment by zcdliuwei** [comment]
mark +1

**Comment by YibooZhao** [comment]
mark

**Comment by lymanzhao** [comment]
I was looking forward to it

**Comment by lymanzhao** [comment]
Is there an expected time?

**Comment by Dibbidy** [comment]
+1

**Comment by ukenmisneru** [comment]
mark

**Comment by liuyifan6613** [comment]
+1.

**Comment by zishen-ucap** [comment]
+10086

**Comment by Jcx12138** [comment]
+1

**Comment by Jeff-LiangF** [comment]
Hi @MahdiMohseni0033 @ghyghoo8 @zcdliuwei @YibooZhao @lymanzhao @Dibbidy @ukenmisneru @liuyifan6613 @zishen-ucap @Jcx12138 and friends who are interested in our FlowVid:

After half a year of negotiations, I regret to inform you that we are unable to release the FlowVid checkpoints. I understand this is disappointing to the community, and I sincerely apologize to let you down. I recommend checking out [TokenFlow](https://github.com/omerbt/TokenFlow), which has on-par results as our FlowVid, and our [StreamV2V](https://github.com/Jeff-LiangF/streamv2v), the fastest video-to-video model available. Although I cannot release the checkpoints, I am permitted to share code snippets upon request. If you are interested in exploring the implementations, please contact me at [jeffliang@utexas.edu](mailto:jeffliang@utexas.edu), and I will guide you to the code.
